mbstat/kirovstat/urls.py
from django.urls import path,re_path

from . import views
from . import views2
from .models import teams

app_name = 'kirovstat'
urlpatterns = [
    path('', views.index, name = 'index'),  
    # path('team_info/<int:team_id>/', views.team_info,  name = 'team_info'),
    re_path(r'^team_info/', views.team_info,  name = 'team_info'),
    re_path(r'^game_info/', views.game_info,  name = 'game_info'),
    #re_path(r'^statistic/', views.game_info,  name = 'stats'),
    re_path(r'^load_game/', views2.add_game,  name = 'load_game'),
    re_path(r'^year_stat/', views.year_stat,  name = 'year_stat'),
    re_path(r'^statstat/', views2.add_res_to_stat,  name = 'statstat'),
    re_path(r'^ratings/', views2.ratings,  name = 'ratings'),
    re_path(r'^compare/', views.compare,  name = 'compare'),
    
]

mbstat/mbstat/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('kirovstat/', include ('kirovstat.urls')),

]

mbstat/kirovstat/models.py
from django.db import models


class game_type(models.Model):
    type_name=models.CharField(verbose_name='Вид игры',max_length=50)

    class Meta: 
       verbose_name_plural = 'Типы игры' 
       verbose_name = 'Тип игры' 
       ordering = ['type_name'] 


    def __str__(self):
        return self.type_name

class teams (models.Model):
    t_name = models.CharField(verbose_name='Название команды',max_length=50)
    t_aka = models.ForeignKey('self',blank=True,null=True,on_delete=models.SET_NULL)
    t_page = models.URLField(default='http://rudagames.ru')
    t_foto = models.CharField(verbose_name='Фото команды',default='.foto.jpg',max_length=50)
    time_data = models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано') 
    
    class Meta: 
       verbose_name_plural = 'Команды' 
       verbose_name = 'Команда' 
       ordering = ['t_name'] 

    def __str__(self):
        return self.t_name
    
class games (models.Model):
    g_name = models.CharField(default="Название игры", max_length=100)
    g_type = models.ForeignKey(game_type,null=True, on_delete=models.SET_NULL)
    g_date = models.DateField(verbose_name='Дата игры')
    g_sets = models.IntegerField(verbose_name='Количесто туров',default=5)
    g_url = models.URLField(verbose_name='Ссылка на игра в ВК',default="https://vk.com/mzgb_kir", max_length=200)
    time_data = models.DateTimeField(auto_now=True,db_index=True, verbose_name='создано') 
    g_teams = models.IntegerField(verbose_name='Количество команда',null=True, default = 1)

    class Meta: 
       verbose_name_plural = 'Игра' 
       verbose_name = 'Игры' 
       ordering = ['-g_date'] 

    def __str__(self):
        return self.g_name 
    
class gmdata (models.Model):
    gd_game = models.ForeignKey(games, verbose_name='Игра',null=False, on_delete = models.CASCADE)
    gd_team = models.ForeignKey(teams, verbose_name='Команда',null=False, on_delete = models.CASCADE)
    gd_set1 = models.FloatField(verbose_name='Тур 1',max_length=5,default=300)
    gd_set2 = models.FloatField(verbose_name='Тур 2',max_length=5,default=300)
    gd_set3 = models.FloatField(verbose_name='Тур 3',max_length=5,default=300)
    gd_set4 = models.FloatField(verbose_name='Тур 4',max_length=5,default=300)
    gd_set5 = models.FloatField(verbose_name='Тур 5',max_length=5,default=300)
    gd_set6 = models.FloatField(verbose_name='Тур 6',max_length=5,default=300)
    gd_set7 = models.FloatField(verbose_name='Тур 7',max_length=5,default=300)
    gd_set8 = models.FloatField(verbose_name='Тур 8',max_length=5,default=300)
    gd_set9 = models.FloatField(verbose_name='Тур 9',max_length=5,default=300)
    gd_set10 = models.FloatField(verbose_name='Тур 10',max_length=5,default=300)
    gd_summ = models.FloatField(max_length=8, verbose_name='Сумма очков')
    gd_place = models.IntegerField(verbose_name='Место')
    time_data = models.DateTimeField(auto_now=True, db_index=True, verbose_name='создано') 

    class Meta: 
       verbose_name_plural = 'Данные' 
       verbose_name = 'Данные' 
       ordering = ['time_data'] 

    def __str__(self):
        self.ret1 = self.gd_game.g_name + " - " + str(self.gd_place) + " место "
        return self.ret1
           
class weekr (models.Model):
    
    
    week_start = models.DateField(verbose_name='Начало недели')
    week_end = models.DateField(verbose_name='Конец недели')
    week_points_tuz = models.CharField(verbose_name="Очки команд за музыкалку",max_length=500)
    week_points_class = models.CharField(verbose_name="Очки команд за классику",max_length=500)
    week_points_summ = models.CharField(verbose_name="Очки команд всего",max_length=500)
    week_rating_tuz = models.CharField(verbose_name="Рейтинг за музыкалку",max_length=800)
    week_rating_class = models.CharField(verbose_name="Рейтинг за классику",max_length=1200)
    week_rating_summ = models.CharField(verbose_name="Рейтинг всего",max_length=2000)
    

    class Meta: 
       verbose_name_plural = 'Статистика по неделям' 
       verbose_name = 'Статистика' 
       ordering = ['week_start'] 

mbstat/kirovstat/views.py
from django.shortcuts import render
from django.http import HttpResponse 
from django.http import JsonResponse
from django.db.models import Avg, Max, Min, Sum
from . models import game_type, games, teams, gmdata, weekr
from . defs_1 import * 
from . defs_2 import *
from . defs_3 import *


def index(request): 
    g_count = get_games_count('2025-01-01','2025-12-31')
    #game1 = games.objects.all() 
    game1 = get_games_all_in_range('2025-01-01','2025-12-31')
    t_data = get_all_teams()     
    year=2025 

    
    place_data_a_1=get_place(1,type1=[1,2,3,4,5]) 
    place_data_a_2=get_place(2,type1=[1,2,3,4,5]) 
    place_data_a_3=get_place(3,type1=[1,2,3,4,5]) 
    place_data_cl_1=get_place(1,type1=[1,5]) 
    place_data_cl_2=get_place(2,type1=[1,5]) 
    place_data_cl_3=get_place(3,type1=[1,5]) 
    place_data_tz_1=get_place(1,type1=[2]) 
    place_data_tz_2=get_place(2,type1=[2]) 
    place_data_tz_3=get_place(3,type1=[2])
    place_data_tem_1=get_place(1,type1=[3])  
    place_data_tem_2=get_place(2,type1=[3])  
    place_data_tem_3=get_place(3,type1=[3])  
    
    context = {
       #'rating_5_tuz': rating_5_tuz, 'rating_5_class': rating_5_class,'rating_5_summ': rating_5_summ,\
               'game1': game1, 'g_count' : g_count, 't_data' : t_data, 'year' : year, \
               'place_data_a_1' : place_data_a_1, 'place_data_a_2' : place_data_a_2,'place_data_a_3' : place_data_a_3,\
               'place_data_cl_1' : place_data_cl_1, 'place_data_cl_2' : place_data_cl_2,'place_data_cl_3' : place_data_cl_3,\
               'place_data_tz_1' : place_data_tz_1, 'place_data_tz_2' : place_data_tz_2,'place_data_tz_3' : place_data_tz_3,\
               'place_data_tem_1' : place_data_tem_1, 'place_data_tem_2' : place_data_tem_2,'place_data_tem_3' : place_data_tem_3 }
 
    
    return render(request, 'game_list.html', context)   

    

def team_info (request):

    test1 = request.GET
    team_id= test1['team_id']
    try:
       year = test1['year']
    except:
       year='2025'
    t_data = get_all_teams()
    # Основной ID команды
    main_id = teams.objects.values('t_aka_id').get(pk=team_id)['t_aka_id']
    # все названия команды
    t_names = teams.objects.filter(t_aka=main_id)
    t_foto = teams.objects.values('t_foto').get(pk=main_id)['t_foto']
    
    akas_list=get_akas(main_id)
    s_data = year + '-01-01'
    f_data = year + '-12-31'
    t_data_info = get_games_info (akas_list,s_data,f_data)
    
    Max_place,Min_place,g_count, \
    l_p,l_p_class,l_p_tuz, \
    l_p_tem,l_p_jub=get_team_year_results(t_data_info)

   
    l=[1,2,3,4,5,6,7,8,9,10]
    
    graph_tuz,graph_class,graph_summ = build_graph_team(t_id=team_id)
          

    context = {'team_id':team_id,'t_data_info': t_data_info, 't_names': t_names, 't_foto': t_foto, \
               't_data':t_data,'Max_place': Max_place,'Min_place' :Min_place, 'g_count':g_count, \
               'l': l,'l_p' : l_p,'l_p_class' : l_p_class,'l_p_tuz' : l_p_tuz, \
               'l_p_tem' :l_p_tem,'l_p_jub':l_p_jub , 'year' : year,\
               'graph_tuz':graph_tuz,'graph_class':graph_class,'graph_summ':graph_summ}
    
    return render(request, 'team_info.html', context)



def game_info (request):
    
    game_id = request.GET['game_id']
    g_data_info = gmdata.objects.filter(gd_game = game_id).order_by('gd_place')
    game_info =  games.objects.get(pk=game_id)
    
    a = games.objects.get(pk=game_id).g_sets
    year = games.objects.values('g_date').get(pk=game_id)['g_date'].year
    game_date = str(games.objects.values('g_date').get(pk=game_id)['g_date'])
    
    tours=[]
    for i in range(1, a+1): 
       tours.append(i)

    tuz_r=get_top10_teams_rating(type_of_data='tuz',game_date=game_info.g_date)
    summ_r=get_top10_teams_rating(type_of_data='summ',game_date=game_info.g_date)
    class_r=get_top10_teams_rating(type_of_data='class',game_date=game_info.g_date)


    if request.user.is_authenticated:
       change_yes=1
    else: change_yes=0

    
    
    context = {'g_data_info': g_data_info, 'year' : year, 'game_info': game_info, 'tours' : tours,\
                'change_yes' : change_yes, 'game_date' : game_date,\
                'summ_r' : summ_r, 'class_r' : class_r,'tuz_r' : tuz_r
              }
    
    return render (request, 'game_info.html', context )


def year_stat(request): 
    year = request.GET['year']
    s_data = year + '-01-01'
    f_data = year + '-12-31'
    g_count = get_games_count(s_data,f_data)
    #game1 = games.objects.all() 
    game1 = get_games_all_in_range(s_data,f_data)
    t_data = get_all_teams()     

    
    place_data_a_1=get_place(1,type1=[1,2,3,4,5],data_start = s_data, data_finish = f_data) 
    place_data_a_2=get_place(2,type1=[1,2,3,4,5],data_start = s_data, data_finish = f_data) 
    place_data_a_3=get_place(3,type1=[1,2,3,4,5],data_start = s_data, data_finish = f_data) 
    place_data_cl_1=get_place(1,type1=[1,5],data_start = s_data, data_finish = f_data) 
    place_data_cl_2=get_place(2,type1=[1,5],data_start = s_data, data_finish = f_data) 
    place_data_cl_3=get_place(3,type1=[1,5],data_start = s_data, data_finish = f_data) 
    place_data_tz_1=get_place(1,type1=[2],data_start = s_data, data_finish = f_data) 
    place_data_tz_2=get_place(2,type1=[2],data_start = s_data, data_finish = f_data) 
    place_data_tz_3=get_place(3,type1=[2],data_start = s_data, data_finish = f_data)
    place_data_tem_1=get_place(1,type1=[3],data_start = s_data, data_finish = f_data)  
    place_data_tem_2=get_place(2,type1=[3],data_start = s_data, data_finish = f_data)  
    place_data_tem_3=get_place(3,type1=[3],data_start = s_data, data_finish = f_data)  
     

    context = {'game1': game1, 'g_count' : g_count, 't_data' : t_data, 'year' : year, \
               'place_data_a_1' : place_data_a_1, 'place_data_a_2' : place_data_a_2,'place_data_a_3' : place_data_a_3,\
               'place_data_cl_1' : place_data_cl_1, 'place_data_cl_2' : place_data_cl_2,'place_data_cl_3' : place_data_cl_3,\
               'place_data_tz_1' : place_data_tz_1, 'place_data_tz_2' : place_data_tz_2,'place_data_tz_3' : place_data_tz_3,\
               'place_data_tem_1' : place_data_tem_1, 'place_data_tem_2' : place_data_tem_2,'place_data_tem_3' : place_data_tem_3 }
 
    
    return render(request, 'year_stat.html', context)   

def compare (request):

   compare_yes=0
   context1={}
   context2={}
   context3={}
   t_data = get_all_teams() 

   if request.method == 'GET' and request.GET.get('team_id1') and request.GET.get('team_id2'):
      compare_yes=1
      team_id1 = request.GET['team_id1']
      team_id2 = request.GET['team_id2']
      try:
        year = request.GET['year']
      except:
        year='2025'

      
      main_id1 = teams.objects.values('t_aka_id').get(pk=team_id1)['t_aka_id']
      t_names1 = teams.objects.filter(t_aka=main_id1)
      
      akas_list1=get_akas(main_id1)
      s_data = year + '-01-01'
      f_data = year + '-12-31'
      t_data_info1 = get_games_info (akas_list1,s_data,f_data)
      Max_place1,Min_place1,g_count1, \
      l_p1,l_p_class1,l_p_tuz1, \
      l_p_tem1,l_p_jub1=get_team_year_results(t_data_info1)

      main_id2 = teams.objects.values('t_aka_id').get(pk=team_id2)['t_aka_id']
      t_names2 = teams.objects.filter(t_aka=main_id2)
      
      akas_list2=get_akas(main_id2)
      s_data = year + '-01-01'
      f_data = year + '-12-31'
      t_data_info2 = get_games_info (akas_list2,s_data,f_data)
      Max_place2,Min_place2,g_count2, \
      l_p2,l_p_class2,l_p_tuz2, \
      l_p_tem2,l_p_jub2=get_team_year_results(t_data_info2)

      context1 = {'t_data_info1': t_data_info1, 't_names1': t_names1, \
               'Max_place1': Max_place1,'Min_place1' :Min_place1, 'g_count1':g_count1, \
               'l_p1' : l_p1,'l_p_class1' : l_p_class1,'l_p_tuz1' : l_p_tuz1, \
               'l_p_tem1' :l_p_tem1,'l_p_jub1':l_p_jub1}  
      context2 = {'t_data_info2': t_data_info2, 't_names2': t_names2, \
               'Max_place2': Max_place2,'Min_place2' :Min_place2, 'g_count2':g_count2, \
               'l_p2' : l_p2,'l_p_class2' : l_p_class2,'l_p_tuz2' : l_p_tuz2, \
               'l_p_tem2' :l_p_tem2,'l_p_jub2':l_p_jub2} 
      
      graph_tuz,graph_class,graph_summ = build_graph_team_compare(t_id1=team_id1,t_id2=team_id2)

      context3 = {'graph_tuz':graph_tuz,'graph_class':graph_class,'graph_summ':graph_summ}
               
   compared_teams=[1,2]

   context={'compare_yes' : compare_yes, 't_data' :t_data, 'compared_teams' : compared_teams } | context1  | context2 | context3

   return render(request, 'compare.html', context )

mbstat/kirovstat/templates/add_game_file.html
{% extends 'base.html' %}
{% block content %}

<body>
    <h1>Добавить файл с игрой</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        
        <button type="submit">Import</button>
    </form>
</body>




{% endblock %}

mbstat/kirovstat/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}    

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>  Мозгобойня Киров. Статистика</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" type="image/png" href="{% static 'favicon-96x96.png' %}" sizes="96x96" />
    <link rel="icon" type="image/svg+xml" href="{% static 'favicon.svg' %}" >
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}" />
    <style>
        a {
            text-decoration: none;
        }
  </style>

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href={% url "kirovstat:index" %} class="navbar-brand">Мозгобойня в Кирове</a>
            <span class="navbar-text">
                <a href="/admin/" class="me-2" target="_blank">Admin</a>
            </span>
        </div>
    </nav>
   <main class = 'container'>
        {% block content %}

        {% endblock  %}
   </main>    
</body>
</html>

mbstat/kirovstat/templates/compare.html
{% extends "base.html" %}
{% block content %}

{% load static %}


<h3>Сравнение команд</h3>
<br>
<form action = "/kirovstat/compare/"  method="get" target="_self">
<Table>
<td>
   <h4>Команда 1  </h4>
   <select class="js-select2" name="team_id1" placeholder="Выберите команду">
   <option value=""></option>
   {% for t in t_data %}
	   <option value={{t.id}}>{{t.t_name}}</option>
	{%endfor%}	
   </select>
   <link rel="stylesheet" href="{% static '/select2/dist/css/select2.min.css' %}">
   <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
   <script src="{% static 'select2/dist/js/select2.min.js' %}"></script>
   <script src="{% static 'select2/dist/js/i18n/ru.js' %}"></script>
   <script>
      $(document).ready(function() {
         $('.js-select2').select2({
            placeholder: "Выберите команду",
            maximumSelectionLength: 2,
            language: "ru"
         });
      });
      </script>
</td>
<td>
   <h4>Команда 2  </h4>
   <select class="js-select2" name="team_id2" placeholder="Выберите команду">
   <option value=""></option>
   {% for t in t_data%}
	   <option value={{t.id}} >{{t.t_name}}</option>
	{%endfor%}	
   </select>
   <link rel="stylesheet" href="{% static '/select2/dist/css/select2.min.css' %}">
   <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
   <script src="{% static 'select2/dist/js/select2.min.js' %}"></script>
   <script src="{% static 'select2/dist/js/i18n/ru.js' %}"></script>
   <script>
      $(document).ready(function() {
         $('.js-select2').select2({
            placeholder: "Выберите команду",
            maximumSelectionLength: 2,
            language: "ru"
         });
      });
      </script>
</td>
<td>
<h4>Выберите год:</h4>
<select id="year" name="year">
   <option value=2025>2025</option>
   <option value=2024>2024</option>
   <option value=2023>2023</option>
   <option value=2022>2022</option>
   <option value=2021>2021</option>
   <option value=2020>2020</option>
   <option value=2019>2019</option>
   <option value=2018>2018</option> 
   <option value=2017>2017</option> 
   <option value=2016>2016</option>  
</select>
</td>
</Table>


<br><button type="submit">Сравнить</button>

</form>

{% if compare_yes == 1 %}
   
   
   <table class = 'table mt-1 table-bordered table-striped table-hover'>

    <tr>
     <td>
      
      {% for t in t_names1%}<br>
      {%if t.id == t.t_aka_id%}
      <h3> {{t.t_name}} </h3>
      {%else%}
      aka - {{t.t_name}}
      {%endif%}  
      {%endfor%} 
     </td>
     <td>
      
      {% for t in t_names2%}<br>
      {%if t.id == t.t_aka_id%}
      <h3> {{t.t_name}} </h3>
      {%else%}
      aka - {{t.t_name}}
      {%endif%}  
      {%endfor%} 
     </td>
    </tr>
    <tr>
      <td>
        <ul>
        <li>Всего игр - {{g_count1}} </li>
        <li>Самое высокое место -  {{Max_place1}} </li>
        <li>Самое низкое место -  {{Min_place1}} </li>
        <li>Побед всего - {{l_p1.1}} </li>
        <li>Побед в классике -  {{l_p_class1.1}} </li>
        <li>Побед в музыке -  {{l_p_tuz1.1}} </li>
        <li>Побед в тематике -  {{l_p_tem1.1}} </li>
        </ul>
      </td>
      <td>
        <li>Всего игр - {{g_count2}} </li>
        <li>Самое высокое место -  {{Max_place2}} </li>
        <li>Самое низкое место -  {{Min_place2}} </li>
        <li>Побед всего - {{l_p2.1}} </li>
        <li>Побед в классике -  {{l_p_class2.1}} </li>
        <li>Побед в музыке -  {{l_p_tuz2.1}} </li>
        <li>Побед в тематике -  {{l_p_tem2.1}} </li>
       </td>
      </tr>
   </table>

   <img src="data:image/png;base64,{{ graph_summ }}" alt="" >
   <img src="data:image/png;base64,{{ graph_tuz }}" alt="" >
   <img src="data:image/png;base64,{{ graph_class }}" alt="" >

{% endif %}





{% endblock %}

mbstat/kirovstat/templates/game_info.html
{% extends "base.html" %}
{% block content %}


<br>
<div>{{ game_info.g_name}}       <a class="btn btn-primary btn-sm" href={{game_info.g_url}} target="_blank" role="button"> VK </a></div>

<br>

<table class = 'table mt-1 table-bordered table-striped table-hover' >
    <thead class="table-dark">
        <tr>
            <th scope="col">Название</th>
            {% for t in tours %}
                 <th scope="col">{{t}}</th>
            {% endfor %} 
            <th scope="col">Итог</th>
            <th scope="col">Место</th>
            {% if change_yes == 1 %}
                <th scope="col">Изменить</th>
            {% endif %}       
        </tr>
    </thead>
    <tbody>
        {% for g_data in g_data_info %}
        <tr>
            <td scope="col"><a href=/kirovstat/team_info/?team_id={{g_data.gd_team_id}}&year={{year}} > <b>{{g_data.gd_team}}</b></a></td>
            <td scope="col">{{g_data.gd_set1}}</td>
            <td scope="col">{{g_data.gd_set2}}</td>           
            <td scope="col">{{g_data.gd_set3}}</td>
            <td scope="col">{{g_data.gd_set4}}</td>
            <td scope="col">{{g_data.gd_set5}}</td>
            {% if game_info.g_sets > 5  %}
                <td scope="col">{{g_data.gd_set6}}</td>
            {% endif %}
            {% if game_info.g_sets > 6 %}
                <td scope="col">{{g_data.gd_set7}}</td>
            {% endif %}
            {% if game_info.g_sets > 7  %}
                <td scope="col">{{g_data.gd_set8}}</td>
            {% endif %}
            {% if game_info.g_sets > 8  %}
                <td scope="col">{{g_data.gd_set9}}</td>
            {% endif %}
            {% if game_info.g_sets > 9  %}
                <td scope="col">{{g_data.gd_set10}}</td>
            {% endif %}
            
            <td scope="col">{{g_data.gd_summ}}</td>
            <td scope="col">{{g_data.gd_place}}</td>
            {% if change_yes == 1 %}
                <th scope="col"><a class="btn btn-primary btn-sm" href=/admin/kirovstat/gmdata/{{g_data.id}}/change >  </a></a></th>
            {% endif %}       
        </tr>
        {% endfor %} 
    </tbody>
</table>

<p><a href=/kirovstat/ratings/?date={{game_date}} > Рейтинг на момент игры </a>
<table>
    <td>
    <ul><b> Общий</b><br>
    {% for key,values in summ_r.items %}
    <li>
       <a href=/kirovstat/team_info/?team_id={{key}}&year={{year}} >{{values.0}} </a>-  {{values.1}}  <br>
    </li>
    {%endfor%}
    </ul>
    </td>   
    <td>
    <ul><b> Классика</b><br>
        {% for key,values in class_r.items %}
        <li>
           <a href=/kirovstat/team_info/?team_id={{key}}&year={{year}} >{{values.0}} </a>-  {{values.1}}  <br>
        </li>
        {%endfor%}
        </ul>
    </td> 
    <td>
        <ul><b> Музыка</b><br>
            {% for key,values in tuz_r.items %}
            <li>
               <a href=/kirovstat/team_info/?team_id={{key}}&year={{year}} >{{values.0}} </a>-  {{values.1}}  <br>
            </li>
            {%endfor%}
            </ul>
    </td>  

</table>


<div><a href="javascript:window.history.back();"><button type="button" class="btn btn-dark">Назад</button></a></button>

{% endblock %}

mbstat/kirovstat/templates/load_game.html
{% extends 'base.html' %}
{% block content %}

<br>

Игра - {{ gl }} <br>

{% for i in dl %}
 
   {{i}} <br>

{%endfor%}


_______________________<br>
Добавить команду  <a class="related-widget-wrapper-link add-related" id="add_id_gd_team" data-popup="yes" href="/admin/kirovstat/teams/add/?_popup=1" target="_blank" title="Добавить ещё один объект типа " Команда""=""><img src="/static/admin/img/icon-addlink.svg"  alt="Добавить"></a><br>
Добавить игру  <a class="related-widget-wrapper-link add-related" id="add_id_gd_team" data-popup="yes" href="/admin/kirovstat/games/add/?_popup=1" target="_blank" title="Добавить ещё один объект типа " Игра""=""><img src="/static/admin/img/icon-addlink.svg"  alt="Добавить"></a><br>

_______________________<br>
<h4>Внести данные</h4>


<a href="/kirovstat/load_game/?add_yes=add_yes" target="_self"><button input type="submit" >Внести</button>





{% endblock %}

mbstat/kirovstat/templates/ratings.html
{% extends 'base.html' %}
{% block content %}

<body>

  <div><h3>Рейтинг команд</h3></div>
  <div></div>Рейтинг подсчитывается по системе подсчета очков  FIA (Formula 1). 
  Учитываются баллы команды за каждую игру 10 первых мест по схеме  1 место - 25 очков, 2е - 18, 3e - 15,
  4е  - 12, 5е - 10, 6е - 8, 7е -6, 8е - 4,9е - 2, 10е-1.  
  На каждую неделю (воскресенье) учитывается сумма данных очков за предыдущие 26 недель (пол-года)</div>
  <p><h4>Общий рейтинг<h4>
    <img src="data:image/png;base64,{{ graph_summ }}" alt="" >
  <p><h4>Рейтинг за классику<h4>
    <p><img src="data:image/png;base64,{{ graph_class }}" alt="" >
  <p><h4>Рейтинг за музыку<h4>
    <p><img src="data:image/png;base64,{{ graph_tuz }}" alt="" >

 <p> <button type="button" class="btn btn-dark" onclick="window.history.back(); return true;">Назад</button>
</body>




{% endblock %}

mbstat/kirovstat/templates/statstat.html
{% extends 'base.html' %}
{% block content %}

<body>

   {{res}}

</body>




{% endblock %}

mbstat/kirovstat/templates/test1.html
{% extends 'base.html' %}
{% block content %}

    <body>
       <div> <h3>  Тестовая картинка</h3>
        
       <img src="data:image/png;base64,{{ graph1 }}" alt="" height="250" ,width="250">
   >   </div>
    </body>




{% endblock %}